package kr.or.mrhi.letsgodaengdaeng.retrofitData.Clinic

data class Row(
    val APVCANCELYMD: String,
    val APVPERMYMD: String,
    val BPLCNM: String,
    val CLGENDDT: String,
    val CLGSTDT: String,
    val DCBYMD: String,
    val DTLSTATEGBN: String,
    val DTLSTATENM: String,
    val LASTMODTS: String,
    val LINDJOBGBNNM: String,
    val LINDPRCBGBNNM: String,
    val LINDSEQNO: String,
    val MGTNO: String,
    val OPNSFTEAMCODE: String,
    val RDNPOSTNO: String,
    val RDNWHLADDR: String,
    val RGTMBDSNO: String,
    val ROPNYMD: String,
    val SITEAREA: String,
    val SITEPOSTNO: String,
    val SITETEL: String,
    val SITEWHLADDR: String,
    val TOTEPNUM: String,
    val TRDSTATEGBN: String,
    val TRDSTATENM: String,
    val UPDATEDT: String,
    val UPDATEGBN: String,
    val UPTAENM: String,
    val X: String,
    val Y: String
)